development: &defaults
  connection:
    :access_key_id: <%= ENV["S3_ACCESS_KEY_ID"] %>
    :secret_access_key: <%= ENV["S3_SECRET_ACCESS_KEY"] %>
    :use_ssl: true
    # :persistent: true
  bucket: <%= ENV["S3_BUCKET"] %>
  max_file_size: 10485760
  acl: public-read

test:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults